// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCatboxAuth(arg1, arg2) {
  return window['go']['db']['Queries']['CreateCatboxAuth'](arg1, arg2);
}

export function DeleteCatboxAuth(arg1, arg2) {
  return window['go']['db']['Queries']['DeleteCatboxAuth'](arg1, arg2);
}

export function GetCatboxAuth(arg1, arg2) {
  return window['go']['db']['Queries']['GetCatboxAuth'](arg1, arg2);
}

export function UpdateCatboxAuth(arg1, arg2) {
  return window['go']['db']['Queries']['UpdateCatboxAuth'](arg1, arg2);
}

export function WithTx(arg1) {
  return window['go']['db']['Queries']['WithTx'](arg1);
}
