// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {db} from '../models';
import {sql} from '../models';

export function CreateCatboxAuth(arg1:context.Context,arg2:string):Promise<db.CatboxAuth>;

export function DeleteCatboxAuth(arg1:context.Context,arg2:number):Promise<void>;

export function GetCatboxAuth(arg1:context.Context,arg2:number):Promise<db.CatboxAuth>;

export function UpdateCatboxAuth(arg1:context.Context,arg2:db.UpdateCatboxAuthParams):Promise<void>;

export function WithTx(arg1:sql.Tx):Promise<db.Queries>;
