// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseFile():Promise<string>;

export function RemovePathFromFile(arg1:string):Promise<string>;

export function SaveIntPreference(arg1:number):Promise<void>;

export function SaveStringPreference(arg1:string):Promise<void>;

export function UploadViaLobfile(arg1:string):Promise<void>;

export function UploadViaPomf(arg1:string):Promise<void>;
