// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function ChooseFile():Promise<string>;

export function Hosts():Promise<{[key: string]: types.Uploader}>;

export function RemovePathFromFile(arg1:string):Promise<string>;

export function SaveHost(arg1:types.Uploader,arg2:Array<number>):Promise<void>;

export function SaveTimeoutDuration(arg1:number,arg2:Array<number>):Promise<void>;
