// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseFile() {
  return window['go']['main']['App']['ChooseFile']();
}

export function RemovePathFromFile(arg1) {
  return window['go']['main']['App']['RemovePathFromFile'](arg1);
}

export function SaveHost(arg1) {
  return window['go']['main']['App']['SaveHost'](arg1);
}

export function SaveTimeoutDuration(arg1) {
  return window['go']['main']['App']['SaveTimeoutDuration'](arg1);
}

export function UploadViaLobfile(arg1) {
  return window['go']['main']['App']['UploadViaLobfile'](arg1);
}

export function UploadViaPomf(arg1) {
  return window['go']['main']['App']['UploadViaPomf'](arg1);
}
